// src/shared/errors/error-codes.ts
export const ErrorCode = {

  // ─── Autenticação & Autorização ────────────────────────────
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_MALFORMED: 'AUTH_TOKEN_MALFORMED',
  AUTH_REFRESH_MISSING: 'AUTH_REFRESH_MISSING',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_EXPIRED: 'AUTH_REFRESH_EXPIRED',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

  // ─── Autorização / Permissões ──────────────────────────────
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_ROLE_INSUFFICIENT: 'PERMISSION_ROLE_INSUFFICIENT',
  PERMISSION_OWN_ONLY: 'PERMISSION_OWN_ONLY',
  PERMISSION_CANNOT_SELF_DEACTIVATE: 'PERMISSION_CANNOT_SELF_DEACTIVATE',
  PERMISSION_ONLY_SUPER_ADMIN: 'PERMISSION_ONLY_SUPER_ADMIN',

  // ─── Usuários ──────────────────────────────────────────────
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_WRONG_PASSWORD: 'USER_WRONG_PASSWORD',
  USER_WEAK_PASSWORD: 'USER_WEAK_PASSWORD',
  USER_INVALID_ROLE: 'USER_INVALID_ROLE',
  USER_ALREADY_INACTIVE: 'USER_ALREADY_INACTIVE',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
  USER_SAME_PASSWORD: 'USER_SAME_PASSWORD',

  // ─── Artigos ───────────────────────────────────────────────
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
  ARTICLE_SLUG_TAKEN: 'ARTICLE_SLUG_TAKEN',
  ARTICLE_INVALID_STATUS: 'ARTICLE_INVALID_STATUS',
  ARTICLE_INVALID_TYPE: 'ARTICLE_INVALID_TYPE',
  ARTICLE_CANNOT_PUBLISH: 'ARTICLE_CANNOT_PUBLISH',
  ARTICLE_CANNOT_ARCHIVE: 'ARTICLE_CANNOT_ARCHIVE',
  ARTICLE_CATEGORY_REQUIRED: 'ARTICLE_CATEGORY_REQUIRED',
  ARTICLE_CONTENT_REQUIRED: 'ARTICLE_CONTENT_REQUIRED',
  ARTICLE_TITLE_REQUIRED: 'ARTICLE_TITLE_REQUIRED',
  ARTICLE_TITLE_TOO_LONG: 'ARTICLE_TITLE_TOO_LONG',
  ARTICLE_SCHEDULED_PAST: 'ARTICLE_SCHEDULED_PAST',
  ARTICLE_IMAGE_NOT_FOUND: 'ARTICLE_IMAGE_NOT_FOUND',
  ARTICLE_NO_IMAGE_UPLOADED: 'ARTICLE_NO_IMAGE_UPLOADED',
  ARTICLE_CATEGORY_NOT_FOUND: 'ARTICLE_CATEGORY_NOT_FOUND',
  ARTICLE_FORBIDDEN_EDIT: 'ARTICLE_FORBIDDEN_EDIT',
  ARTICLE_FORBIDDEN_DELETE: 'ARTICLE_FORBIDDEN_DELETE',
  ARTICLE_TRANSITION_INVALID: 'ARTICLE_TRANSITION_INVALID',
  ARTICLE_FEATURED_CANNOT_ARCHIVE: 'ARTICLE_FEATURED_CANNOT_ARCHIVE',

  // ─── Categorias ────────────────────────────────────────────
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_TAKEN: 'CATEGORY_NAME_TAKEN',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
  CATEGORY_HAS_ARTICLES: 'CATEGORY_HAS_ARTICLES',
  CATEGORY_NAME_REQUIRED: 'CATEGORY_NAME_REQUIRED',
  CATEGORY_COLOR_INVALID: 'CATEGORY_COLOR_INVALID',

  // ─── Tags ──────────────────────────────────────────────────
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_NAME_TAKEN: 'TAG_NAME_TAKEN',
  TAG_NAME_REQUIRED: 'TAG_NAME_REQUIRED',
  TAG_NAME_TOO_LONG: 'TAG_NAME_TOO_LONG',
  TAG_HAS_ARTICLES: 'TAG_HAS_ARTICLES',

  // ─── Banners ───────────────────────────────────────────────
  BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',
  BANNER_IMAGE_REQUIRED: 'BANNER_IMAGE_REQUIRED',
  BANNER_TITLE_REQUIRED: 'BANNER_TITLE_REQUIRED',
  BANNER_DATE_RANGE_INVALID: 'BANNER_DATE_RANGE_INVALID',
  BANNER_DATE_PAST: 'BANNER_DATE_PAST',

  // ─── Menu ──────────────────────────────────────────────────
  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',
  MENU_LABEL_REQUIRED: 'MENU_LABEL_REQUIRED',
  MENU_URL_REQUIRED: 'MENU_URL_REQUIRED',
  MENU_URL_INVALID: 'MENU_URL_INVALID',
  MENU_PARENT_NOT_FOUND: 'MENU_PARENT_NOT_FOUND',
  MENU_CIRCULAR_REFERENCE: 'MENU_CIRCULAR_REFERENCE',
  MENU_MAX_DEPTH_EXCEEDED: 'MENU_MAX_DEPTH_EXCEEDED',
  MENU_LABEL_TAKEN: 'MENU_LABEL_TAKEN',
  MENU_CATEGORY_ALREADY_IN_USE: 'MENU_CATEGORY_ALREADY_IN_USE',

  // ─── Configurações ─────────────────────────────────────────
  SETTINGS_NOT_FOUND: 'SETTINGS_NOT_FOUND',
  SETTINGS_COLOR_INVALID: 'SETTINGS_COLOR_INVALID',
  SETTINGS_URL_INVALID: 'SETTINGS_URL_INVALID',
  SETTINGS_LOGO_REQUIRED: 'SETTINGS_LOGO_REQUIRED',

  // ─── Upload / Imagens ──────────────────────────────────────
  UPLOAD_NO_FILE: 'UPLOAD_NO_FILE',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_CLOUDINARY_FAILED: 'UPLOAD_CLOUDINARY_FAILED',
  UPLOAD_DELETE_FAILED: 'UPLOAD_DELETE_FAILED',
  UPLOAD_CORRUPTED_FILE: 'UPLOAD_CORRUPTED_FILE',
  UPLOAD_EMPTY_FILE: 'UPLOAD_EMPTY_FILE',

  // ─── Paginação / Query ─────────────────────────────────────
  PAGINATION_PAGE_INVALID: 'PAGINATION_PAGE_INVALID',
  PAGINATION_LIMIT_INVALID: 'PAGINATION_LIMIT_INVALID',
  PAGINATION_LIMIT_TOO_HIGH: 'PAGINATION_LIMIT_TOO_HIGH',

  // ─── Banco de dados ────────────────────────────────────────
  DB_UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DB_FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',

  // ─── Live Scores ───────────────────────────────────────────
  LIVE_SCORES_API_KEY_MISSING: 'LIVE_SCORES_API_KEY_MISSING',
  LIVE_SCORES_API_UNAVAILABLE: 'LIVE_SCORES_API_UNAVAILABLE',
  LIVE_SCORES_API_RATE_LIMITED: 'LIVE_SCORES_API_RATE_LIMITED',
  LIVE_SCORES_TEAM_NOT_FOUND: 'LIVE_SCORES_TEAM_NOT_FOUND',
  LIVE_SCORES_MATCHDAY_INVALID: 'LIVE_SCORES_MATCHDAY_INVALID',
  LIVE_SCORES_DATE_RANGE_INVALID: 'LIVE_SCORES_DATE_RANGE_INVALID',
  LIVE_SCORES_STATUS_INVALID: 'LIVE_SCORES_STATUS_INVALID',

  // ─── Validação Genérica ────────────────────────────────────
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_UUID: 'VALIDATION_INVALID_UUID',
  VALIDATION_INVALID_DATE: 'VALIDATION_INVALID_DATE',
  VALIDATION_INVALID_URL: 'VALIDATION_INVALID_URL',
  VALIDATION_STRING_TOO_SHORT: 'VALIDATION_STRING_TOO_SHORT',
  VALIDATION_STRING_TOO_LONG: 'VALIDATION_STRING_TOO_LONG',
  VALIDATION_NUMBER_OUT_OF_RANGE: 'VALIDATION_NUMBER_OUT_OF_RANGE',
  VALIDATION_BODY_MISSING: 'VALIDATION_BODY_MISSING',
  VALIDATION_JSON_INVALID: 'VALIDATION_JSON_INVALID',
  VALIDATION_PARAM_INVALID: 'VALIDATION_PARAM_INVALID',
  VALIDATION_QUERY_INVALID: 'VALIDATION_QUERY_INVALID',

  // ─── Sistema ───────────────────────────────────────────────
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  ENV_MISSING: 'ENV_MISSING',
  SCHEDULER_ERROR: 'SCHEDULER_ERROR',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  TIMEOUT: 'TIMEOUT',

  // ─── Patrocinadores ────────────────────────────────────────
  SPONSOR_NOT_FOUND: 'SPONSOR_NOT_FOUND',
  SPONSOR_NAME_REQUIRED: 'SPONSOR_NAME_REQUIRED',
  SPONSOR_IMAGE_REQUIRED: 'SPONSOR_IMAGE_REQUIRED',
  SPONSOR_NAME_TAKEN: 'SPONSOR_NAME_TAKEN',

  // ─── Eventos ───────────────────────────────────────────────
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_TITLE_REQUIRED: 'EVENT_TITLE_REQUIRED',
  EVENT_SLUG_TAKEN: 'EVENT_SLUG_TAKEN',
  EVENT_DATE_REQUIRED: 'EVENT_DATE_REQUIRED',
  EVENT_DATE_RANGE_INVALID: 'EVENT_DATE_RANGE_INVALID',
  EVENT_IMAGE_NOT_FOUND: 'EVENT_IMAGE_NOT_FOUND',
  EVENT_DESCRIPTION_REQUIRED: 'EVENT_DESCRIPTION_REQUIRED',

} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];